ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal  # Important for Docker!
      user: dataeng
      password: dataeng123
      port: 5432
      dbname: ecommerce
      schema: analytics
      threads: 4